[package]
name = "implot-sys-bindgen"
version = "0.4.0"
authors = ["Sandro Merkli"]
edition = "2018"

[dependencies]
bindgen = "0.69.0"
imgui-sys = { version = "0.11.0", features=["docking"]}
lazy_static = "1.4.0"
regex = "1.10.2"
